
from core.domotica_exception import DomoticaException

class NetworkException(DomoticaException):
    pass
