from core.domotica_exception import DomoticaException

class ControlCoreException(DomoticaException):
    pass
